---
title: "Info"
author: "Garth Tarr"
date: "20 March 2015"
output: html_document
---

### Financial data 

The financial data example is loaded by default.  The data comes from the `huge` R package:

```
require(huge)
data(stockdata)
X = log(stockdata$data[2:1258,]/stockdata$data[1:1257,])
```

The estimated covariance matrices are pre-computed and loaded with the shiny app.  This makes things faster for the financial data than if you uplaod your own data.

### Upload csv file

The csv file should contain a data matrix.  Optionally, the first row can contain the variable names.

### Upload RData file

The RData file should contain a named list of length two with names `data` and `info`.  The `data` should be a numeric matrix and the `info` should contain data frame with the names of the variables in one column and a grouping identifier in the second column (if applicable).

For example

```
> str(data)
List of 2
 $ data: num [1:1258, 1:452] 127 126 127 127 126 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:452] "V1" "V2" "V3" "V4" ...
 $ info: chr [1:452, 1:2] "MMM" "ACE" "ABT" "ANF" ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:2] "V1" "V2"
> data$data[1:5,1:5]
         V1    V2    V3    V4    V5
[1,] 126.75 30.51 40.05 21.75 25.60
[2,] 126.27 30.69 40.44 21.34 26.30
[3,] 127.19 31.97 40.70 22.11 27.51
[4,] 127.07 31.78 38.87 22.07 28.51
[5,] 125.70 31.17 39.85 22.40 27.13
> data$info[1:5,]
     V1     V2                      
[1,] "MMM"  "Industrials"           
[2,] "ACE"  "Financials"            
[3,] "ABT"  "Health Care"           
[4,] "ANF"  "Consumer Discretionary"
[5,] "ADBE" "Information Technology"
```

If there is no `info` component in the RData upload, it will be assumed that the names of the variables are the column names from the data matrix.
